services:
  service-1:
    build:
      context: ./service_1
      dockerfile: Dockerfile
    container_name: service-1
    expose:
      - "8001"
    networks:
      - system-c-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8001/ping",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
      
  service-2:
    build:
      context: ./service_2
      dockerfile: Dockerfile
    container_name: service-2
    expose:
      - "8002"
    networks:
      - system-c-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8002/ping",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-reverse-proxy
    ports:
      - "8000:8000"
    depends_on:
      - service-1
      - service-2
    networks:
      - system-c-network
    volumes:
      - ./logs:/var/log/nginx
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8000/nginx-health",
        ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  system-c-network:
    driver: bridge
